name: End-to-End Tests
on:
  workflow_run:
    workflows: ["Deploy to Staging"]
    types: [completed]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1
        
      - name: Run API tests
        run: |
          pnpm test:api --baseURL=https://staging-api.yourapp.com
          
      - name: Run browser tests
        run: |
          pnpm test:e2e --baseURL=https://staging.yourapp.com
          
      - name: Run performance tests
        run: |
          pnpm test:performance --target=https://staging.yourapp.com
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-results
          path: |
            test-results/
            playwright-report/
            
      - name: Update QA status
        run: |
          curl -X POST https://api.yourapp.com/qa-status \
               -H "Authorization: Bearer ${{ secrets.QA_API_TOKEN }}" \
               -d '{"sha":"${{ github.sha }}","status":"tested","passed":true}'
