name: Post Deploy Verification
# on:
#   workflow_run:
#     workflows: ["Deploy to Production"]
#     types: [completed]

jobs:
  post-deploy-checks:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Smoke tests
        run: |
          # Critical path verification
          curl -f https://yourapp.com/api/health
          curl -f https://yourapp.com/login
          curl -f https://yourapp.com/dashboard
          
      - name: Database migration verification
        run: |
          # Verify migrations completed successfully
          kubectl exec deployment/app-backend -- npm run db:verify-migrations
          
      - name: Performance baseline check
        run: |
          # Quick performance check
          curl -w "@curl-format.txt" -o /dev/null https://yourapp.com/
          
      - name: Setup monitoring alerts
        run: |
          # Enable production monitoring
          curl -X POST https://api.datadog.com/api/v1/monitor \
               -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
               -d '{"type":"metric alert","query":"avg(last_5m):avg:app.response_time > 1000"}'
               
      - name: Notify team of successful deployment
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#deployments'
          message: 'Production deployment complete: ${{ github.sha }}'