on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Source
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "frontendDev" ]; then
            echo "Error: Only PRs from 'frontendDev' are allowed into 'main'."
            exit 1
          fi
      - name: Deploy to Production
        if: success()
        run: echo "Deploying to production..."
